version: '3.8'

volumes:
  nextcloud:
  db:
  minio:
  onlyoffice-document-server:
  redis:
  document_data:
  redis_data:
services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8081"]
    interval: 30s
    timeout: 10s
    retries: 5
  minio:
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/data/minio
        target: /mnt/data
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /mnt/data/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001"]
      interval: 30s
      timeout: 10s
      retries: 5
  onlyoffice-document-server:
    restart: unless-stopped
    image: onlyoffice/documentserver
    ports:
      - "80:80"
    environment:
      - JWT_ENABLED=${JWT_ENABLES}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - redis_data:/var/lib/redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    restart: unless-stopped
    image: redis:alpine
    volumes:
      - redis_data:/data
